custom_hostname: P1
custom_router_isis:
  instance: CORE
  eos_cli: |-
    traffic-engineering
      no shutdown
      is-type level-1
custom_ethernet_interfaces:
  - name: Ethernet1
    eos_cli: |-
      traffic-engineering
  - name: Ethernet2
    eos_cli: |-
      traffic-engineering
  - name: Ethernet3
    eos_cli: |-
      traffic-engineering
  - name: Ethernet4
    eos_cli: |-
      traffic-engineering
custom_router_traffic_engineering:
  #enabled: true
  segment_routing:
  router_id:
    ipv4: 192.168.101.1