hostname: PE4
router_isis:
  instance: CORE
  segment_routing_mpls:
    enabled: true
    router_id: 192.168.0.101.24
  eos_cli: |-
    address-family ipv4 unicast
      multi-topology
    traffic-engineering
      no shutdown
      is-type level-1
